- name: Deploy edX Video Pipeline Service
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    migrate_db: 'yes'
    edx_django_service_use_python3: false
  roles:
    - role: nginx
      nginx_default_sites:
        - video_pipeline
    - edxlocal
    - role: video_pipeline
