---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role edx-video-pipeline
#


#
# vars are namespace with the module name.
#
video_pipeline_service_name: "video_pipeline"
video_pipeline_gunicorn_port: 8555

video_pipeline_user: "{{ video_pipeline_service_name }}"
video_pipeline_home: "{{ COMMON_APP_DIR }}/{{ video_pipeline_service_name }}"

# TODO! Find some better way to do the below
video_pipeline_service_home: "{{ COMMON_APP_DIR }}/{{ video_pipeline_service_name }}"
video_pipeline_code_dir: "{{ video_pipeline_service_home }}/{{ video_pipeline_service_name }}"

video_pipeline_environment: {}

video_pipeline_ingest_worker: "{{ video_pipeline_service_name }}_ingest"
video_pipeline_deliver_worker: "{{ video_pipeline_service_name }}_deliver"

#
# OS packages
#

video_pipeline_debian_pkgs:
  - libffi6
  - libffi-dev

VIDEO_PIPELINE_NGINX_PORT: "1{{ video_pipeline_gunicorn_port }}"
VIDEO_PIPELINE_SSL_NGINX_PORT: "4{{ video_pipeline_gunicorn_port }}"

VIDEO_PIPELINE_DEFAULT_DB_NAME: "pipeline"
VIDEO_PIPELINE_MYSQL: "localhost"
# MySQL usernames are limited to 16 characters
VIDEO_PIPELINE_MYSQL_USER: "pipeline001"
VIDEO_PIPELINE_MYSQL_PASSWORD: "password"

VIDEO_PIPELINE_MEMCACHE: []

VIDEO_PIPELINE_VERSION: "master"
VIDEO_PIPELINE_DJANGO_SETTINGS_MODULE: "VEDA.settings"
VIDEO_PIPELINE_URL_ROOT: "http://pipeline:{{ VIDEO_PIPELINE_NGINX_PORT }}"
VIDEO_PIPELINE_LOGOUT_URL: "{{ VIDEO_PIPELINE_URL_ROOT }}/logout/"

VIDEO_PIPELINE_SECRET_KEY: "Your secret key here"
VIDEO_PIPELINE_LANGUAGE_CODE: "en-us"

# Used to automatically configure OAuth2 Client
VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_KEY : "pipeline-key"
VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_SECRET : "pipeline-secret"
VIDEO_PIPELINE_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false

VIDEO_PIPELINE_DATA_DIR: "{{ COMMON_DATA_DIR }}/{{ video_pipeline_service_name }}"
VIDEO_PIPELINE_MEDIA_ROOT: "{{ VIDEO_PIPELINE_DATA_DIR }}/media"
VIDEO_PIPELINE_MEDIA_URL: "/media/"

VIDEO_PIPELINE_MEDIA_STORAGE_BACKEND:
  DEFAULT_FILE_STORAGE: "django.core.files.storage.FileSystemStorage"
  MEDIA_ROOT: "{{ VIDEO_PIPELINE_MEDIA_ROOT }}"
  MEDIA_URL: "{{ VIDEO_PIPELINE_MEDIA_URL }}"

VIDEO_PIPELINE_STATICFILES_STORAGE: "django.contrib.staticfiles.storage.StaticFilesStorage"

VIDEO_PIPELINE_GUNICORN_EXTRA: ""

VIDEO_PIPELINE_EXTRA_APPS: []

# See edx_django_service_automated_users for an example of what this should be
VIDEO_PIPELINE_AUTOMATED_USERS: {}

# instance_config.yaml variable overrides
# TODO! add sane default values for below variables
VIDEO_PIPELINE_EDX_S3_INGEST_PREFIX: "SET-ME-PLEASE"
VIDEO_PIPELINE_EDX_S3_INGEST_BUCKET: "video_pipeline_edx_s3_ingest_bucket"
VIDEO_PIPELINE_EDX_S3_ENDPOINT_BUCKET: "video_pipeline_edx_s3_endpoint_bucket"

VIDEO_PIPELINE_EDX_CLOUDFRONT_PREFIX: "video_pipeline_edx_cloudfront_prefix"
VIDEO_PIPELINE_VEDA_S3_UPLOAD_BUCKET: "video_pipeline_veda_s3_upload_bucket"
VIDEO_PIPELINE_VEDA_S3_HOTSTORE_BUCKET: "video_pipeline_veda_s3_hotstore_bucket"
VIDEO_PIPELINE_VEDA_DELIVERABLE_BUCKET: "video_pipeline_veda_deliverable_bucket"
VIDEO_PIPELINE_VEDA_BASE_URL: "veda.edx.org"
VIDEO_PIPELINE_VEDA_SECRET_ACCESS_KEY: "video_pipeline_veda_secret_access_key"
VIDEO_PIPELINE_VEDA_ACCESS_KEY_ID: "video_pipeline_veda_access_key_id"
VIDEO_PIPELINE_VEDA_NOREPLY_EMAIL: "video_pipeline_veda_noreply_email"

VIDEO_PIPELINE_AWS_VIDEO_IMAGES_BUCKET: "video_pipeline_aws_video_images_bucket"
VIDEO_PIPELINE_AWS_VIDEO_TRANSCRIPTS_BUCKET: "video_pipeline_aws_video_transcripts_bucket"

VIDEO_PIPELINE_ADMIN_EMAIL: "video_pipeline_admin_email"

VIDEO_PIPELINE_CIELO24_API_ENVIRONMENT: "video_pipeline_cielo24_api_environment"
VIDEO_PIPELINE_TRANSCRIPT_PROVIDER_REQUEST_TOKEN: "video_pipeline_transcript_provider_request_token"

VIDEO_PIPELINE_VEDA_API_URL: "video_pipeline_veda_api_url"
VIDEO_PIPELINE_VEDA_AUTH_URL: "video_pipeline_veda_auth_url"
VIDEO_PIPELINE_VEDA_CLIENT_ID: "video_pipeline_veda_client_id"
VIDEO_PIPELINE_VEDA_SECRET_KEY: "video_pipeline_veda_secret_key"
VIDEO_PIPELINE_VEDA_TOKEN_URL: "video_pipeline_veda_token_url"

VIDEO_PIPELINE_VAL_API_URL: "video_pipeline_val_api_url"
VIDEO_PIPELINE_VAL_TOKEN_URL: "video_pipeline_val_token_url"
VIDEO_PIPELINE_VAL_VIDEO_IMAGES_URL: "video_pipeline_val_video_images_url"
VIDEO_PIPELINE_VAL_CLIENT_ID: "video_pipeline_val_client_id"
VIDEO_PIPELINE_VAL_SECRET_KEY: "video_pipeline_val_secret_key"
VIDEO_PIPELINE_VAL_PASSWORD: "video_pipeline_val_password"
VIDEO_PIPELINE_VAL_USERNAME: "video_pipeline_val_username"
VIDEO_PIPELINE_VAL_TRANSCRIPT_CREATE_URL: "video_pipeline_val_transcript_create_url"
VIDEO_PIPELINE_VAL_VIDEO_TRANSCRIPT_STATUS_URL: "video_pipeline_val_video_transcript_status_url"

VIDEO_PIPELINE_RABBITMQ_BROKER: "localhost"
VIDEO_PIPELINE_RABBITMQ_PASS: "veda"
VIDEO_PIPELINE_RABBITMQ_USER: "veda"

VIDEO_PIPELINE_SG_SERVER_PATH: "video_pipeline_sg_server_path"
VIDEO_PIPELINE_SG_SCRIPT_NAME: "video_pipeline_sg_script_name"
VIDEO_PIPELINE_SG_SCRIPT_KEY: "video_pipeline_sg_script_key"

VIDEO_PIPELINE_THREEPLAY_FTPHOST: "video_pipeline_threeplay_ftphost"

VIDEO_PIPELINE_XUETANG_API_URL: "video_pipeline_xuetang_api_url"
VIDEO_PIPELINE_XUETANG_API_SHARED_SECRET: "video_pipeline_xuetang_api_shared_secret"
