---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role edx-video-pipeline
#


#
# vars are namespace with the module name.
#
video_pipeline_service_name: "video_pipeline"
video_pipeline_gunicorn_port: 8555

video_pipeline_user: "{{ video_pipeline_service_name }}"
video_pipeline_home: "{{ COMMON_APP_DIR }}/{{ video_pipeline_service_name }}"

# TODO! Find some better way to do the below
video_pipeline_service_home: "{{ COMMON_APP_DIR }}/{{ video_pipeline_service_name }}"
video_pipeline_code_dir: "{{ video_pipeline_service_home }}/{{ video_pipeline_service_name }}"

video_pipeline_environment: {}

video_pipeline_ingest_worker: "{{ video_pipeline_service_name }}_ingest"
video_pipeline_deliver_worker: "{{ video_pipeline_service_name }}_deliver"

#
# OS packages
#

video_pipeline_debian_pkgs:
  - libffi6
  - libffi-dev

VIDEO_PIPELINE_NGINX_PORT: "1{{ video_pipeline_gunicorn_port }}"
VIDEO_PIPELINE_SSL_NGINX_PORT: "4{{ video_pipeline_gunicorn_port }}"

VIDEO_PIPELINE_DEFAULT_DB_NAME: "pipeline"
VIDEO_PIPELINE_MYSQL: "localhost"
# MySQL usernames are limited to 16 characters
VIDEO_PIPELINE_MYSQL_USER: "pipeline001"
VIDEO_PIPELINE_MYSQL_PASSWORD: "password"

VIDEO_PIPELINE_MEMCACHE: []

VIDEO_PIPELINE_VERSION: "master"
VIDEO_PIPELINE_DJANGO_SETTINGS_MODULE: "VEDA.settings"
VIDEO_PIPELINE_URL_ROOT: "http://pipeline:{{ VIDEO_PIPELINE_NGINX_PORT }}"
VIDEO_PIPELINE_LOGOUT_URL: "{{ VIDEO_PIPELINE_URL_ROOT }}/logout/"

VIDEO_PIPELINE_SECRET_KEY: "Your secret key here"
VIDEO_PIPELINE_LANGUAGE_CODE: "en-us"

# Used to automatically configure OAuth2 Client
VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_KEY : "pipeline-key"
VIDEO_PIPELINE_SOCIAL_AUTH_EDX_OIDC_SECRET : "pipeline-secret"
VIDEO_PIPELINE_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false

VIDEO_PIPELINE_DATA_DIR: "{{ COMMON_DATA_DIR }}/{{ video_pipeline_service_name }}"
VIDEO_PIPELINE_MEDIA_ROOT: "{{ VIDEO_PIPELINE_DATA_DIR }}/media"
VIDEO_PIPELINE_MEDIA_URL: "/media/"

VIDEO_PIPELINE_MEDIA_STORAGE_BACKEND:
  DEFAULT_FILE_STORAGE: "django.core.files.storage.FileSystemStorage"
  MEDIA_ROOT: "{{ VIDEO_PIPELINE_MEDIA_ROOT }}"
  MEDIA_URL: "{{ VIDEO_PIPELINE_MEDIA_URL }}"

VIDEO_PIPELINE_STATICFILES_STORAGE: "django.contrib.staticfiles.storage.StaticFilesStorage"

VIDEO_PIPELINE_GUNICORN_EXTRA: ""

VIDEO_PIPELINE_EXTRA_APPS: []

# See edx_django_service_automated_users for an example of what this should be
VIDEO_PIPELINE_AUTOMATED_USERS: {}

# instance_config.yaml variable overrides

VIDEO_PIPELINE_EDX_CLOUDFRONT_PREFIX: "SET-ME-PLEASE"
VIDEO_PIPELINE_EDX_S3_INGEST_PREFIX: "ingest/"
VIDEO_PIPELINE_EDX_S3_INGEST_BUCKET: "SET-ME-PLEASE"
VIDEO_PIPELINE_EDX_S3_ENDPOINT_BUCKET: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_S3_UPLOAD_BUCKET: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_UPLOAD_BUCKET: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_S3_HOTSTORE_BUCKET: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_DELIVERABLE_BUCKET: "SET-ME-PLEASE"

VIDEO_PIPELINE_VEDA_BASE_URL: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_ACCESS_KEY_ID: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_SECRET_ACCESS_KEY: "SET-ME-PLEASE"

VIDEO_PIPELINE_AWS_VIDEO_IMAGES_BUCKET: "SET-ME-PLEASE"
VIDEO_PIPELINE_AWS_VIDEO_TRANSCRIPTS_BUCKET: "SET-ME-PLEASE"

VIDEO_PIPELINE_ADMIN_EMAIL: "veda@example.com"
VIDEO_PIPELINE_VEDA_NOREPLY_EMAIL: "veda-noreply@example.com"

VIDEO_PIPELINE_CIELO24_API_ENVIRONMENT: "sandbox"
VIDEO_PIPELINE_TRANSCRIPT_PROVIDER_REQUEST_TOKEN: "SET-ME-TO-A-UNIQUE-LONG-RANDOM-STRING"

VIDEO_PIPELINE_VEDA_API_URL: "{{ VIDEO_PIPELINE_VEDA_BASE_URL }}/api"
VIDEO_PIPELINE_VEDA_AUTH_URL: "{{ VIDEO_PIPELINE_VEDA_BASE_URL }}/veda_auth"
VIDEO_PIPELINE_VEDA_CLIENT_ID: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_SECRET_KEY: "SET-ME-PLEASE"
VIDEO_PIPELINE_VEDA_TOKEN_URL: "{{ VIDEO_PIPELINE_VEDA_BASE_URL }}/o/token"

VIDEO_PIPELINE_VAL_BASE_URL: "http://127.0.0.1:8010"
VIDEO_PIPELINE_VAL_API_URL: "{{ VIDEO_PIPELINE_VAL_BASE_URL }}/api/val/v0/videos"
VIDEO_PIPELINE_VAL_TOKEN_URL: "{{ VIDEO_PIPELINE_VAL_BASE_URL }}/oauth2/access_token"
VIDEO_PIPELINE_VAL_VIDEO_IMAGES_URL: "{{ VIDEO_PIPELINE_VAL_BASE_URL }}/api/val/v0/videos/video-images/update/"
VIDEO_PIPELINE_VAL_CLIENT_ID: "SET-ME-PLEASE"
VIDEO_PIPELINE_VAL_SECRET_KEY: "SET-ME-PLEASE"
VIDEO_PIPELINE_VAL_USERNAME: "staff"
VIDEO_PIPELINE_VAL_PASSWORD: "edx"
VIDEO_PIPELINE_VAL_TRANSCRIPT_CREATE_URL: "{{ VIDEO_PIPELINE_VAL_BASE_URL }}/api/val/v0/videos/video-transcripts/create/"
VIDEO_PIPELINE_VAL_VIDEO_TRANSCRIPT_STATUS_URL: "{{ VIDEO_PIPELINE_VAL_BASE_URL }}/api/val/v0/videos/status/"

VIDEO_PIPELINE_RABBITMQ_BROKER: "localhost"
VIDEO_PIPELINE_RABBITMQ_PASS: "veda"
VIDEO_PIPELINE_RABBITMQ_USER: "veda"

VIDEO_PIPELINE_SG_SERVER_PATH: "SET-ME-PLEASE"
VIDEO_PIPELINE_SG_SCRIPT_NAME: "SET-ME-PLEASE"
VIDEO_PIPELINE_SG_SCRIPT_KEY: "SET-ME-PLEASE"

VIDEO_PIPELINE_THREEPLAY_FTPHOST: "SET-ME-PLEASE"

VIDEO_PIPELINE_XUETANG_API_URL: "SET-ME-PLEASE"
VIDEO_PIPELINE_XUETANG_API_SHARED_SECRET: "SET-ME-PLEASE"
